"""
Created on Mon Jul 15 14:50:50 2019
@author: aliPMPAINT
"""
import numpy as np
import matplotlib.pyplot as plt
x = np.linspace(-3.14159, 3.14159, 1000)
ysec = 1/(np.cos(x))
ysecm = np.ma.masked_where(np.abs(ysec) > 25, ysec)
ytan = (np.sin(x))/(np.cos(x))
ytanm = np.ma.masked_where(np.abs(ytan) > 25, ytan)
ycot = (np.cos(x))/(np.sin(x))
ycotm = np.ma.masked_where(np.abs(ycot) > 25, ycot)
ycsc = 1/(np.sin(x))
ycscm = np.ma.masked_where(np.abs(ycsc) > 25, ycsc)
yx = 1/x
yxm = np.ma.masked_where(np.abs(yx) > 25, yx)
ynx = -1/x
ynxm = np.ma.masked_where(np.abs(ynx) > 25, ynx)
plt.subplot(3, 2, 1)
plt.figure(1, figsize=(20,20))
plt.plot(x, ysecm, "b-", label="Secant Function")
plt.ylim(-20, 20)
plt.ylabel("Secant Values")
plt.xlabel("x in radians")
plt.legend(loc="upper right", title="Secant Function")
plt.axhline(y=0, zorder=-1)
plt.axvline(x=0, zorder=-1)
plt.axvline(x=((np.pi)/2), color="red", zorder=1)
plt.axvline(x=((np.pi)/-2), color="red", zorder=1)
plt.subplot(3, 2, 2)
plt.figure(1, figsize=(20,20))
plt.plot(x, ytanm, "b-", label="Tangent Function")
plt.ylim(-20, 20)
plt.ylabel("Tangent Values")
plt.xlabel("x in radians")
plt.legend(loc="upper right", title="Tangent Function")
plt.axhline(y=0, zorder=-1)
plt.axvline(x=0, zorder=-1)
plt.axvline(x=((np.pi)/2), color="red", zorder=1)
plt.axvline(x=((np.pi)/-2), color="red", zorder=1)
plt.subplot(3, 2, 3)
plt.figure(1, figsize=(20,20))
plt.plot(x, ycotm, "b-", label="Cotangent Function")
plt.ylim(-20, 20)
plt.ylabel("Cotangent Values")
plt.xlabel("x in radians")
plt.legend(loc="upper right", title="Cotangent Function")
plt.axhline(y=0, zorder=-1)
plt.axvline(x=0, zorder=-1)
plt.axvline(x=((np.pi)/2), color="red", zorder=1)
plt.axvline(x=((np.pi)/-2), color="red", zorder=1)
plt.subplot(3, 2, 4)
plt.figure(1, figsize=(20,20))
plt.plot(x, ycscm, "b-", label="Cosecant Function")
plt.ylim(-20, 20)
plt.ylabel("Cosecant Values")
plt.xlabel("x in radians")
plt.legend(loc="upper right", title="Cosecant Function")
plt.axhline(y=0, zorder=-1)
plt.axvline(x=0, zorder=-1)
plt.axvline(x=((np.pi)/2), color="red", zorder=1)
plt.axvline(x=((np.pi)/-2), color="red", zorder=1)
plt.savefig("Secant.png")
plt.show()
plt.subplot(3, 2, 5)
plt.figure(1, figsize=(20,20))
plt.plot(x, yxm, "b-", label="I Function")
plt.ylim(-20, 20)
plt.ylabel("I Values")
plt.xlabel("x in radians")
plt.legend(loc="upper right", title="I Function")
plt.axhline(y=0, zorder=-1)
plt.axvline(x=0, zorder=-1)
plt.axvline(x=((np.pi)/2), color="red", zorder=1)
plt.axvline(x=((np.pi)/-2), color="red", zorder=1)
plt.subplot(3, 2, 6)
plt.figure(1, figsize=(20,20))
plt.plot(x, ynxm, "b-", label="NL Function")
plt.ylim(-20, 20)
plt.ylabel("NL Values")
plt.xlabel("x in radians")
plt.legend(loc="upper right", title="NL Function")
plt.axhline(y=0, zorder=-1)
plt.axvline(x=0, zorder=-1)
plt.axvline(x=((np.pi)/2), color="red", zorder=1)
plt.axvline(x=((np.pi)/-2), color="red", zorder=1)
plt.tight_layout()
plt.savefig("HELP!.png")
plt.show()
